### PR TITLE
Show replica status, closes #272

### LINKED ISSUE #272: Show replica status
For deployments with multiple replicas, it is difficult to grok the overall health of all replicas with only one status indicator. Therefore, we now expose the number of replicas for each status. A component showing this is needed, which could perhaps live by the top bar, like in the following crude photoshop mockup (less wide would look nicer).
Screenshot from 2024-05-15 23-09-30

Inspiration: Rancher replica status overview 
> overview
>image

> expanded
>image

Looks like this in the deployment object
```json
  "replicaStatus": {
    "desiredReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "unavailableReplicas": 0
  }
```

Some conditions:
- Only show for deployments
- Only show when replicas > 1
- Dropdown listing the status (Add i18n locale labels for each status)

### PR DESCRIPTION
**Pull request by Phillezi**
#272 

Shows the status of a deployments replicas, (if replicas > 1)

## The different statuses
* **Ready**: Amount gotten from `readyReplicas` for replicas that are ready, no current action (showed in green)
* **Occupied**: Amount gotten from `availableReplicas - readyReplicas` for replicas that are doing something (showed in blue)
* **Unavailable**: Amount gotten from `unavailableReplicas` for replicas that are unavailable. (showed in red)
* **Desired**: Amount gotten from `desiredReplicas - (availableReplicas + unavailableReplicas)` for replicas that the user wants but doesnt exist. (showed in grey[800], light grey on dark-mode and dark grey on light mode)

## What have i done
* I created a component `ReplicaStatus.tsx` that is displayed inside the `Edit.tsx` top bar  that gets rendered if the `resource.type` is deployment and there are `> 1` replicas on that deployment.
* Added i18n locale entries in `en.json` and `se.json` for the labels used to describe the statuses.

### Deployments with short names
Screenshot from 2024-05-20 22-48-51
### Deployments with longer names
Screenshot from 2024-05-20 22-49-02
### Heres how it looks with more statuses
Screenshot from 2024-05-20 23-03-06
###  With many replicas
Screenshot from 2024-05-20 23-04-47
### i18n locale status labels
image

### CODE REVIEW

**Review by pierrelefevre — CHANGES_REQUESTED** [review]
Hi, thanks for the PR! Made a slight adjustment to the button size and margin, was a bit large imo, hope that's ok.

I think it might be useful to label what this is, for those who haven't seen it before like:
image

Also, not sure why the popup is "clickable", should probably just be Typography or similar component

**Comment by pierrelefevre** [comment]
Huh seems my commit didn't make it, but I edited the spacing to 1 (brings the button closer to the Status view, and added size="small" to the IconButton.

**Comment by pierrelefevre** [comment]
I wonder if it might be beneficial to remove the black border when showing many replicas, seems it gets pretty aliased otherwise?

**Comment by Phillezi** [comment]
Hi!
Thanks for the feedback
* Updated the button size and the spacing.
* Changed from `MenuItem`to `Typography`(not clickable anymore) .
* Added a header to the dropdown with i18n locale.

Does this look good, or should i change anything?
image
image

Havent done the border removal on large amounts yet, but will start with that now

**Comment by pierrelefevre** [comment]
Nice! Maybe some more margin below the header would look good, could base it off the Menu component 
image

**Comment by pierrelefevre** [comment]
> Nice! Maybe some more margin below the header would look good, could base it off the Menu component image

(divider might be unnecessary but do whatever looks best to you :D)

**Comment by Phillezi** [comment]
Added some more margin and changed the color of the divider, looks like this now:

image

image

**Review by pierrelefevre — APPROVED** [review]

**Comment by pierrelefevre** [comment]
Looking good! This will be a great addition to the console. Thanks for your work :)

**Comment by Phillezi** [comment]
Thanks! :)

**Pull request merged**
