### PR TITLE
Add generate random name button next to any name field

### PR DESCRIPTION
**Pull request by Phillezi**
Added randomize name button to the 'RFC1035Input.tsx' component, it can be enabled by adding the optional parameter 'enableRandomize' and setting it to true. Which I enabled for deployments in 'CreateDeployments.tsx' and for vms in 'CreateVm.tsx'.

It uses faker-js to generate a random name for k8s deployments or vms, with the regex used to generate random names when not running as release.

The icon is the one that was recommended in the issue, mdi:dice-3-outline.

#233 

image
image
Screencast from 2024-05-14 08-29-35
(gif quality === very many)

### CODE REVIEW

**Comment by pierrelefevre** [comment]
Thanks for the PR! Cool animation :) Is it ready for review?

**Comment by Phillezi** [comment]
Thanks! :)
Yes, its ready for review now, lmk if there is something i can improve or should do differently.

**Review by pierrelefevre — APPROVED** [review]
LGTM, great work 👍🏻

**Comment by pierrelefevre** [comment]
🎉 Congrats on your first kthcloud PR!

**Comment by Phillezi** [comment]
Thanks! :)

**Pull request merged**
