### PR TITLE
Disable GenAI disclaimer

### PR DESCRIPTION
**Pull request by Sachinsingh2002**
can you please review it.

### CODE REVIEW

**Comment by pierrelefevre** [comment]
Related to #326

**Comment by Sachinsingh2002** [comment]
is it correct now?

**Comment by pierrelefevre** [comment]
Since the i18n strings are gone I think it would make more sense to remove the component instead of commenting it out

**Comment by Sachinsingh2002** [comment]
sure

**Comment by pierrelefevre** [comment]
seems the checks are failing, please follow the formatting instructions in the readme :)

**Pull request merged**
